export const nbaIds = new Map([
	['HAWKS', 1],
	['CELTICS', 2],
	['NETS', 3],	
	['BULLS', 4],
	['CAVALIERS', 5],
	['MAVERICKS', 6],
	['NUGGETS', 7],
	['PISTONS', 8],
	['WARRIORS', 9],
	['ROCKETS', 10],
	['PACERS', 11],
	['CLIPPERS', 12],
	['LAKERS', 13],
	['HEAT', 14],
	['BUCKS', 15],
	['TIMBERWOLVES', 16],
	['PELICANS', 17],
	['KNICKS', 18],
	['THUNDER', 25],
	['MAGIC', 19],
	['SEVENTYSIXERS', 20],
	['SUNS', 21],
	['TRAILBLAZERS', 22],
	['KINGS', 23],
	['SPURS', 24],
])
